<?php
// get all the local field groups 
$field_groups = acf_get_local_field_groups();

// loop over each of the gield gruops 
foreach( $field_groups as $field_group ) {

	// get the field group key 
	$key = $field_group['key'];

	// if this field group has fields 
	if( acf_have_local_fields( $key ) ) {
	
      	// append the fields 
		$field_group['fields'] = acf_get_local_fields( $key );

	}

	// save the acf-json file to the acf-json dir by default 
	acf_write_json_field_group( $field_group );

}
if( function_exists('register_field_group') ):

register_field_group(array (
	'key' => 'group_587aa8a772589',
	'title' => 'Details',
	'fields' => array (
		array (
			'key' => 'field_5900d4c615c03',
			'label' => 'General Information',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_58f96e81b4f9c',
			'label' => 'Listing Price',
			'name' => 'listing_price',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '$',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array (
			'key' => 'field_58f96f50b4f9d',
			'label' => 'Sold Price',
			'name' => 'sold_price',
			'type' => 'number',
			'instructions' => 'When a property has sold enter the sale price here but remove the listing price.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '$',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array (
			'key' => 'field_58f96f89b4f9e',
			'label' => 'Status',
			'name' => 'status',
			'type' => 'select',
			'instructions' => 'Select one from drop down.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Active' => 'Active',
				'Pending' => 'Pending',
				'Sold' => 'Sold',
				'Non-MLS-Active' => 'Non-MLS-Active',
				'Non-MLS-Pending' => 'Non-MLS-Pending',
				'Non-MLS-Sold' => 'Non-MLS-Sold',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array (
			'key' => 'field_58f9702c55d54',
			'label' => 'City',
			'name' => 'city',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_58f97059df903',
			'label' => 'Taxes',
			'name' => 'taxes',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_58876f4481ea2',
			'label' => 'Style of Home',
			'name' => 'style_of_home',
			'type' => 'select',
			'instructions' => 'Select one from drop down.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'multiple' => 0,
			'allow_null' => 0,
			'choices' => array (
				'(SF) One Story\'>(SF) One Story' => '(SF) One Story\'>(SF) One Story',
				'(SF) One 1/2 Stories\'>(SF) One 1/2 Stories' => '(SF) One 1/2 Stories\'>(SF) One 1/2 Stories',
				'(SF) Two Stories\'>(SF) Two Stories' => '(SF) Two Stories\'>(SF) Two Stories',
				'(SF) More Than Two Stories\'>(SF) More Than Two Stories' => '(SF) More Than Two Stories\'>(SF) More Than Two Stories',
				'(SF) Modified Two Story\'>(SF) Modified Two Story' => '(SF) Modified Two Story\'>(SF) Modified Two Story',
				'(SF) Three Level Split\'>(SF) Three Level Split' => '(SF) Three Level Split\'>(SF) Three Level Split',
				'(SF) Split Entry (Bi-Level)\'>(SF) Split Entry (Bi-Level)' => '(SF) Split Entry (Bi-Level)\'>(SF) Split Entry (Bi-Level)',
				'(SF) Four or More Level Split\'>(SF) Four or More Level Split' => '(SF) Four or More Level Split\'>(SF) Four or More Level Split',
				'(SF) Other\'>(SF) Other' => '(SF) Other\'>(SF) Other',
				'(TH) Detached\'>(TH) Detached' => '(TH) Detached\'>(TH) Detached',
				'(TH) Quad/4 Corners\'>(TH) Quad/4 Corners' => '(TH) Quad/4 Corners\'>(TH) Quad/4 Corners',
				'(TH) Side x Side\'>(TH) Side x Side' => '(TH) Side x Side\'>(TH) Side x Side',
				'(TW) Twin Home\'>(TW) Twin Home' => '(TW) Twin Home\'>(TW) Twin Home',
				'(CC) High Rise (4+ Levels)\'>(CC) High Rise (4+ Levels)' => '(CC) High Rise (4+ Levels)\'>(CC) High Rise (4+ Levels)',
				'(CC) Low Rise (3- Levels)\'>(CC) Low Rise (3- Levels)' => '(CC) Low Rise (3- Levels)\'>(CC) Low Rise (3- Levels)',
				'(CC) Manor/Village\'>(CC) Manor/Village' => '(CC) Manor/Village\'>(CC) Manor/Village',
				'(CC) Two Unit\'>(CC) Two Unit' => '(CC) Two Unit\'>(CC) Two Unit',
				'(CC) Converted Mansion\'>(CC) Converted Mansion' => '(CC) Converted Mansion\'>(CC) Converted Mansion',
				'Time Share' => 'Time Share',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_588cecd814097',
			'label' => 'Media',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_587c11ee6256a',
			'label' => 'Virtual Tour 1',
			'name' => 'virtual_tour_1',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_587c12186256b',
			'label' => 'Virtual Tour 2',
			'name' => 'virtual_tour_2',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_589d221f949e6',
			'label' => 'Property Images',
			'name' => 'property_images',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'insert' => 'append',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),		
		array (
			'key' => 'field_5a5eaa82d3855',
			'label' => 'Directions',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5a5eaac5d3856',
			'label' => 'Directions',
			'name' => 'directions',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array (
			'key' => 'field_588ced59262f2',
			'label' => 'Open House',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_587aa92e706a3',
			'label' => 'Open House ',
			'name' => 'open_house_start_time',
			'type' => 'text',
			'instructions' => 'Enter open house time.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			
			/*'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'F j, Y g:i a',
			'return_format' => 'F j, Y g:i a',
			'first_day' => 0,*/
		),
		/*array (
			'key' => 'field_587aa9a0fada3',
			'label' => 'Open House End Time',
			'name' => 'open_house_end_time',
			'type' => 'date_time_picker',
			'instructions' => 'Click on text box to open date time picker',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'F j, Y g:i a',
			'return_format' => 'F j, Y g:i a',
			'first_day' => 0,
		),*/
		array (
			'key' => 'field_588cfae2bd52d',
			'label' => 'Remarks',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_587aaa69637d2',
			'label' => 'Remarks',
			'name' => 'remarks',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'new_lines' => 'wpautop',
			'maxlength' => '',
			'placeholder' => '',
			'rows' => '',
		),
		array (
			'key' => 'field_5900eb7fdf102',
			'label' => 'Bedrooms',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5884f9dc96d35',
			'label' => 'Bedroom1 Level',
			'name' => 'bedroom1_level',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_5884fad396d36',
			'label' => 'Bedroom1 Area',
			'name' => 'bedroom1_area',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_5884fae596d37',
			'label' => 'Bedroom2 Level',
			'name' => 'bedroom2_level',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_5884fb5696d38',
			'label' => 'Bedroom2 Area',
			'name' => 'bedroom2_area',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_5884fcf596d39',
			'label' => 'Bedroom3 Level',
			'name' => 'bedroom3_level',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_5884fd0a96d3a',
			'label' => 'Bedroom3 Area',
			'name' => 'bedroom3_area',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_5884fd1a96d3b',
			'label' => 'Bedroom4 Level',
			'name' => 'bedroom4_level',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_5884fd3d96d3c',
			'label' => 'Bedroom4 Area',
			'name' => 'bedroom4_area',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_5900ebb0df104',
			'label' => 'Bathrooms',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5900f044d5449',
			'label' => 'Total Baths',
			'name' => 'total_baths',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5900f0879e849',
			'label' => 'Full Baths',
			'name' => 'full_baths',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5900f0a0706e1',
			'label' => '3/4 Baths',
			'name' => '34_baths',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5900f0b00ff72',
			'label' => '1/2 Baths',
			'name' => '12_baths',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5887709a81ea7',
			'label' => 'Bath Description',
			'name' => 'bath_description',
			'type' => 'select',
			'instructions' => 'Use control key for multi-selections',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'multiple' => 1,
			'allow_null' => 0,
			'choices' => array (
				'Main Floor Full Bath' => 'Main Floor Full Bath',
				'Main Floor 3/4 Bath' => 'Main Floor 3/4 Bath',
				'Main Floor 1/2 Bath' => 'Main Floor 1/2 Bath',
				'Upper Level Full Bath' => 'Upper Level Full Bath',
				'Upper Level 3/4 Bath' => 'Upper Level 3/4 Bath',
				'Other' => 'Other',
				'Upper Level 1/2 Bath' => 'Upper Level 1/2 Bath',
				'Private Master' => 'Private Master',
				'Full Master' => 'Full Master',
				'1/2 Master' => '1/2 Master',
				'3/4 Master' => '3/4 Master',
				'Master Walk-Thru' => 'Master Walk-Thru',
				'Walk Thru' => 'Walk Thru',
				'Bathroom Ensuite' => 'Bathroom Ensuite',
				'Walk-In Shower Stall' => 'Walk-In Shower Stall',
				'Full Jack & Jill' => 'Full Jack & Jill',
				'3/4 Jack & Jill' => '3/4 Jack & Jill',
				'1/2 Jack & Jill' => '1/2 Jack & Jill',
				'Full Basement' => 'Full Basement',
				'3/4 Basement' => '3/4 Basement',
				'1/2 Basement' => '1/2 Basement',
				'Basement' => 'Basement',
				'Rough In' => 'Rough In',
				'Separate Tub & Shower' => 'Separate Tub & Shower',
				'Whirlpool' => 'Whirlpool',
				'Two Master Baths' => 'Two Master Baths',
				'Two Basement Baths' => 'Two Basement Baths',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
		),
				array (
			'key' => 'field_588cfa9dcfbc7',
			'label' => 'Rooms',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5884f89c9c708',
			'label' => 'Living Rm Level',
			'name' => 'living_rm_level',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_5884f8f59c70a',
			'label' => 'Living Rm Area',
			'name' => 'living_rm_area',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_5884f8c99c709',
			'label' => 'Dining Rm Level',
			'name' => 'dining_rm_level',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_5884f90d9c70b',
			'label' => 'Dining Rm Area',
			'name' => 'dining_rm_area',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
				array (
			'key' => 'field_5887710081ea9',
			'label' => 'Dining Room Description',
			'name' => 'dining_room_description',
			'type' => 'select',
			'instructions' => 'Use control key for multi-selections',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'multiple' => 1,
			'allow_null' => 0,
			'choices' => array (
				'Separate/Formal Dining Room' => 'Separate/Formal Dining Room',
				'Informal Dining Room' => 'Informal Dining Room',
				'Eat In Kitchen' => 'Eat In Kitchen',
				'Breakfast Area' => 'Breakfast Area',
				'Kitchen/Dining Room' => 'Kitchen/Dining Room',
				'Living/Dining Room' => 'Living/Dining Room',
				'Other' => 'Other',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_5884f9409c70c',
			'label' => 'Family Rm Level',
			'name' => 'family_rm_level',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_5884f9549c70d',
			'label' => 'Family Rm Area',
			'name' => 'family_rm_area',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_5887712981eaa',
			'label' => 'Family Room Characteristics',
			'name' => 'family_room_characteristics',
			'type' => 'select',
			'instructions' => 'Use control key for multi-selections',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'multiple' => 1,
			'allow_null' => 0,
			'choices' => array (
				'Main Level' => 'Main Level',
				'Lower Level' => 'Lower Level',
				'2 Story/High/Vaulted Ceilings' => '2 Story/High/Vaulted Ceilings',
				'2 or More' => '2 or More',
				'Great Room' => 'Great Room',
				'Family Room' => 'Family Room',
				'Loft' => 'Loft',
				'Entertainment/Media Center' => 'Entertainment/Media Center',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_5884f9729c70e',
			'label' => 'Kitchen Level',
			'name' => 'kitchen_level',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_5884f9869c70f',
			'label' => 'Kitchen Area',
			'name' => 'kitchen_area',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_5900eb99df103',
			'label' => 'Other Rooms',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5884f7f29c704',
			'label' => 'Extra Room 1',
			'name' => 'extra_room_1',
			'type' => 'select',
			'instructions' => 'Select one from drop down.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'multiple' => 0,
			'allow_null' => 0,
			'choices' => array (
				'Patio' => 'Patio',
				'Play Room' => 'Play Room',
				'Porch' => 'Porch',
				'Recreation Room' => 'Recreation Room',
				'Screened Porch' => 'Screened Porch',
				'Second Kitchen' => 'Second Kitchen',
				'Sitting Room' => 'Sitting Room',
				'Sixth (6th) Bedroom' => 'Sixth (6th) Bedroom',
				'Spa or Sauna Room' => 'Spa or Sauna Room',
				'Storage Room' => 'Storage Room',
				'Studio' => 'Studio',
				'Study' => 'Study',
				'Sun Room' => 'Sun Room',
				'Thee Season Porch' => 'Thee Season Porch',
				'Unfinished' => 'Unfinished',
				'Utility Room' => 'Utility Room',
				'Walk-in Closet' => 'Walk-in Closet',
				'Wine Cellar' => 'Wine Cellar',
				'Workshop' => 'Workshop',
				'Other' => 'Other',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_58850a9496d3d',
			'label' => 'Extra Room 1 Level',
			'name' => 'extra_room_1_level',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_58850abd96d3e',
			'label' => 'Extra Room 1 Area',
			'name' => 'extra_room_1_area',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_5884f8769c705',
			'label' => 'Extra Room 2',
			'name' => 'extra_room_2',
			'type' => 'select',
			'instructions' => 'Select one from drop down.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'multiple' => 0,
			'allow_null' => 0,
			'choices' => array (
				'Patio' => 'Patio',
				'Play Room' => 'Play Room',
				'Porch' => 'Porch',
				'Recreation Room' => 'Recreation Room',
				'Screened Porch' => 'Screened Porch',
				'Second Kitchen' => 'Second Kitchen',
				'Sitting Room' => 'Sitting Room',
				'Sixth (6th) Bedroom' => 'Sixth (6th) Bedroom',
				'Spa or Sauna Room' => 'Spa or Sauna Room',
				'Storage Room' => 'Storage Room',
				'Studio' => 'Studio',
				'Study' => 'Study',
				'Sun Room' => 'Sun Room',
				'Thee Season Porch' => 'Thee Season Porch',
				'Unfinished' => 'Unfinished',
				'Utility Room' => 'Utility Room',
				'Walk-in Closet' => 'Walk-in Closet',
				'Wine Cellar' => 'Wine Cellar',
				'Workshop' => 'Workshop',
				'Other' => 'Other',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_58850b9496d3f',
			'label' => 'Extra Room 2 Level',
			'name' => 'extra_room_2_level',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_58850baf96d40',
			'label' => 'Extra Room 2 Area',
			'name' => 'extra_room_2_area',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_5884f8829c706',
			'label' => 'Extra Room 3',
			'name' => 'extra_room_3',
			'type' => 'select',
			'instructions' => 'Select one from drop down.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'multiple' => 0,
			'allow_null' => 0,
			'choices' => array (
				'Patio' => 'Patio',
				'Play Room' => 'Play Room',
				'Porch' => 'Porch',
				'Recreation Room' => 'Recreation Room',
				'Screened Porch' => 'Screened Porch',
				'Second Kitchen' => 'Second Kitchen',
				'Sitting Room' => 'Sitting Room',
				'Sixth (6th) Bedroom' => 'Sixth (6th) Bedroom',
				'Spa or Sauna Room' => 'Spa or Sauna Room',
				'Storage Room' => 'Storage Room',
				'Studio' => 'Studio',
				'Study' => 'Study',
				'Sun Room' => 'Sun Room',
				'Thee Season Porch' => 'Thee Season Porch',
				'Unfinished' => 'Unfinished',
				'Utility Room' => 'Utility Room',
				'Walk-in Closet' => 'Walk-in Closet',
				'Wine Cellar' => 'Wine Cellar',
				'Workshop' => 'Workshop',
				'Other' => 'Other',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_588515fac0480',
			'label' => 'Extra Room 3 Level',
			'name' => 'extra_room_3_level',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_5885160dc0481',
			'label' => 'Extra Room 3 Area',
			'name' => 'extra_room_3_area',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_5884f8919c707',
			'label' => 'Extra Room 4',
			'name' => 'extra_room_4',
			'type' => 'select',
			'instructions' => 'Select one from drop down.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'multiple' => 0,
			'allow_null' => 0,
			'choices' => array (
				'Patio' => 'Patio',
				'Play Room' => 'Play Room',
				'Porch' => 'Porch',
				'Recreation Room' => 'Recreation Room',
				'Screened Porch' => 'Screened Porch',
				'Second Kitchen' => 'Second Kitchen',
				'Sitting Room' => 'Sitting Room',
				'Sixth (6th) Bedroom' => 'Sixth (6th) Bedroom',
				'Spa or Sauna Room' => 'Spa or Sauna Room',
				'Storage Room' => 'Storage Room',
				'Studio' => 'Studio',
				'Study' => 'Study',
				'Sun Room' => 'Sun Room',
				'Thee Season Porch' => 'Thee Season Porch',
				'Unfinished' => 'Unfinished',
				'Utility Room' => 'Utility Room',
				'Walk-in Closet' => 'Walk-in Closet',
				'Wine Cellar' => 'Wine Cellar',
				'Workshop' => 'Workshop',
				'Other' => 'Other',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_5885163dc0482',
			'label' => 'Extra Room 4 Level',
			'name' => 'extra_room_4_level',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_5885165ac0483',
			'label' => 'Extra Room 4 Area',
			'name' => 'extra_room_4_area',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
				array (
			'key' => 'field_5900fd63ae230',
			'label' => 'Interior',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5900f834fe00d',
			'label' => 'Number of Fireplaces',
			'name' => 'total_fireplaces',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_58876edc81ea1',
			'label' => 'Fireplace(s)',
			'name' => 'number_of_fireplacestype_and_location',
			'type' => 'select',
			'instructions' => 'Use control key for multi-selections',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'multiple' => 1,
			'allow_null' => 0,
			'choices' => array (
				'Living Room' => 'Living Room',
				'Family Room' => 'Family Room',
				'Amusement Room' => 'Amusement Room',
				'Master Bedroom' => 'Master Bedroom',
				'Wood Stove' => 'Wood Stove',
				'Wood Burning' => 'Wood Burning',
				'Gas Burning' => 'Gas Burning',
				'Electric' => 'Electric',
				'Brick' => 'Brick',
				'Stone' => 'Stone',
				'Free Standing' => 'Free Standing',
				'2-Sided' => '2-Sided',
				'Other' => 'Other',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_5904b08b2bcd2',
			'label' => 'Appliances',
			'name' => 'appliances',
			'type' => 'select',
			'instructions' => 'Use control key for multi-selections',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Range' => 'Range',
				'Cooktop' => 'Cooktop',
				'Wall Oven' => 'Wall Oven',
				'Indoor Grill' => 'Indoor Grill',
				'Microwave' => 'Microwave',
				'Exhaust Fan/Hood' => 'Exhaust Fan/Hood',
				'Dishwasher' => 'Dishwasher',
				'Trash Compactor' => 'Trash Compactor',
				'Refrigerator' => 'Refrigerator',
				'Freezer' => 'Freezer',
				'Washer' => 'Washer',
				'Dryer' => 'Dryer',
				'Tankless Water Heater' => 'Tankless Water Heater',
				'Water Softener - Owned' => 'Water Softener - Owned',
				'Water Softener - Rented' => 'Water Softener - Rented',
				'Disposal' => 'Disposal',
				'Central Vacuum' => 'Central Vacuum',
				'Electronic Air Filter' => 'Electronic Air Filter',
				'Air-To-Air Exchanger' => 'Air-To-Air Exchanger',
				'Furnace Humidifier' => 'Furnace Humidifier',
				'Other' => 'Other',
				'None' => 'None',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 1,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array (
			'key' => 'field_5900f261206f3',
			'label' => 'Additional Information',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_588770cd81ea8',
			'label' => 'Amenities',
			'name' => 'amenities',
			'type' => 'select',
			'instructions' => 'Use control key for multi-selections',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'multiple' => 1,
			'allow_null' => 0,
			'choices' => array (
				'Deck' => 'Deck',
				'Patio' => 'Patio',
				'Porch' => 'Porch',
				'Dock' => 'Dock',
				'Natural Woodwork' => 'Natural Woodwork',
				'Hot Tub' => 'Hot Tub',
				'Sauna' => 'Sauna',
				'Balcony' => 'Balcony',
				'Kitchen Window' => 'Kitchen Window',
				'Skylight' => 'Skylight',
				'Vaulted Ceiling(s)' => 'Vaulted Ceiling(s)',
				'Ceiling Fan(s)' => 'Ceiling Fan(s)',
				'Hardwood Floors' => 'Hardwood Floors',
				'Tiled Floors' => 'Tiled Floors',
				'Walk-In Closet' => 'Walk-In Closet',
				'Exercise Room' => 'Exercise Room',
				'Tennis Court' => 'Tennis Court',
				'Sun Room' => 'Sun Room',
				'Washer/Dryer Hookup' => 'Washer/Dryer Hookup',
				'Security System' => 'Security System',
				'Indoor Sprinklers' => 'Indoor Sprinklers',
				'In-Ground Sprinkler' => 'In-Ground Sprinkler',
				'Local Area Network' => 'Local Area Network',
				'Multiple Phone Lines' => 'Multiple Phone Lines',
				'Unspecified' => 'Unspecified',
				'Other' => 'Other',
				'None' => 'None',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_588771d781eae',
			'label' => 'Special Search',
			'name' => 'special_search',
			'type' => 'select',
			'instructions' => 'Use control key for multi-selections',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'multiple' => 1,
			'allow_null' => 0,
			'choices' => array (
				'Main Floor Laundry' => 'Main Floor Laundry',
				'2nd Floor Laundry' => '2nd Floor Laundry',
				'Main Floor Bedroom' => 'Main Floor Bedroom',
				'3 BR on One Level' => '3 BR on One Level',
				'4 BR on One Level' => '4 BR on One Level',
				'All Living Facilities on One Level' => 'All Living Facilities on One Level',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_588771a381ead',
			'label' => 'Pool description',
			'name' => '_pool_description',
			'type' => 'select',
			'instructions' => 'Use control key for multi-selections',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'multiple' => 1,
			'allow_null' => 0,
			'choices' => array (
				'Above Ground' => 'Above Ground',
				'Below Ground' => 'Below Ground',
				'Indoor' => 'Indoor',
				'Outdoor' => 'Outdoor',
				'Heated' => 'Heated',
				'Shared' => 'Shared',
				'None' => 'None',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_588519714eb1b',
			'label' => 'Basement Description',
			'name' => 'basement_description',
			'type' => 'select',
			'instructions' => 'Use control key for multi-selections',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'multiple' => 1,
			'allow_null' => 0,
			'choices' => array (
				'Walkout' => 'Walkout',
				'Full' => 'Full',
				'Partial' => 'Partial',
				'Crawl Space' => 'Crawl Space',
				'Finished (Livable)' => 'Finished (Livable)',
				'Partial Finished' => 'Partial Finished',
				'Drain Tiled' => 'Drain Tiled',
				'Drainage System' => 'Drainage System',
				'Sump Pump' => 'Sump Pump',
				'Day/Lookout Windows' => 'Day/Lookout Windows',
				'Egress Windows' => 'Egress Windows',
				'Concrete Block' => 'Concrete Block',
				'Poured Concrete' => 'Poured Concrete',
				'Insulating Concrete Forms' => 'Insulating Concrete Forms',
				'Slab' => 'Slab',
				'Stone' => 'Stone',
				'Wood' => 'Wood',
				'Unfinished' => 'Unfinished',
				'None' => 'None',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
		),
				array (
			'key' => 'field_590248d04d6b9',
			'label' => 'Parking',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_5904b5bb3b560',
			'label' => 'Garage',
			'name' => 'garage',
			'type' => 'select',
			'instructions' => 'Select one from drop down.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Yes' => 'Yes',
				'No' => 'No',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array (
			'key' => 'field_5904b8c261703',
			'label' => 'Garage Spaces',
			'name' => 'garage_spaces',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_5887705881ea6',
			'label' => 'Parking Characteristics',
			'name' => 'parking_characteristics',
			'type' => 'select',
			'instructions' => 'Use control key for multi-selections',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'multiple' => 1,
			'allow_null' => 0,
			'choices' => array (
				'Attached Garage' => 'Attached Garage',
				'Detached Garage' => 'Detached Garage',
				'Tuckunder' => 'Tuckunder',
				'Tandem' => 'Tandem',
				'Insulated Garage' => 'Insulated Garage',
				'Heated Garage' => 'Heated Garage',
				'Underground Garage' => 'Underground Garage',
				'Covered' => 'Covered',
				'Carport' => 'Carport',
				'Uncovered/Open' => 'Uncovered/Open',
				'Driveway - Gravel' => 'Driveway - Gravel',
				'Driveway - Concrete' => 'Driveway - Concrete',
				'Driveway - Asphalt' => 'Driveway - Asphalt',
				'Driveway - Other Surface' => 'Driveway - Other Surface',
				'Driveway - Shared' => 'Driveway - Shared',
				'Secured' => 'Secured',
				'More Parking Onsite for Fee' => 'More Parking Onsite for Fee',
				'More Parking Offsite for Fee' => 'More Parking Offsite for Fee',
				'Valet Parking for Fee' => 'Valet Parking for Fee',
				'Contract Pkg Required' => 'Contract Pkg Required',
				'Assigned' => 'Assigned',
				'Unassigned' => 'Unassigned',
				'On-Street Parking Only' => 'On-Street Parking Only',
				'Units Vary' => 'Units Vary',
				'Garage Door Opener' => 'Garage Door Opener',
				'No Int Access to Dwelling' => 'No Int Access to Dwelling',
				'Other' => 'Other',
				'None' => 'None',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_588cfee88fd8c',
			'label' => 'Structure',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_587ab78cc86ea',
			'label' => 'Construction Status',
			'name' => 'construction_status',
			'type' => 'select',
			'instructions' => 'Select one from drop down.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Previously Owned' => 'Previously Owned',
				'Completed New Construction' => 'Completed New Construction',
				'Under Construc/Spec Homes' => 'Under Construc/Spec Homes',
				'To Be Built/Floor Plan' => 'To Be Built/Floor Plan',
				'Model (for sale)' => 'Model (for sale)',
				'Model (not for sale)' => 'Model (not for sale)',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array (
			'key' => 'field_587aba212e37d',
			'label' => 'Yearly/Seasonal',
			'name' => 'yearlyseasonal',
			'type' => 'select',
			'instructions' => 'Select one from drop down.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'Yearly' => 'Yearly',
				'Seasonal' => 'Seasonal',
			),
			'default_value' => array (
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array (
			'key' => 'field_587ab7cfc86eb',
			'label' => 'Foundation Size',
			'name' => 'foundation_size',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_587ab80fc86ec',
			'label' => 'Above Grade Fin Sq Ft',
			'name' => 'above_grade_fin_sq_ft',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_587ab8ea4951c',
			'label' => 'Below Grade Fin Sq Ft',
			'name' => 'below_grade_fin_sq_ft',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_587ab914487af',
			'label' => 'Total Fin Sq Ft',
			'name' => 'total_fin_sq_ft',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_58876df381e9e',
			'label' => 'Roof',
			'name' => 'roof',
			'type' => 'select',
			'instructions' => 'Use control key for multi-selections',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'multiple' => 1,
			'allow_null' => 0,
			'choices' => array (
				'Asphalt Shingles' => 'Asphalt Shingles',
				'Pitched' => 'Pitched',
				'Flat' => 'Flat',
				'Unspecified Shingle' => 'Unspecified Shingle',
				'Tar/Gravel' => 'Tar/Gravel',
				'Age 8 Years or Less' => 'Age 8 Years or Less',
				'Age Over 8 Years' => 'Age Over 8 Years',
				'Slate' => 'Slate',
				'Tile' => 'Tile',
				'Shakes' => 'Shakes',
				'Rubber' => 'Rubber',
				'Metal' => 'Metal',
				'Wood Shingles' => 'Wood Shingles',
				'Concrete' => 'Concrete',
				'Other' => 'Other',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_587ab92643d44',
			'label' => 'Acres',
			'name' => 'acres',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_587ab9b34cc5b',
			'label' => 'Lot Size',
			'name' => 'lot_size',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_5887714f81eab',
			'label' => 'A/C',
			'name' => 'ac',
			'type' => 'select',
			'instructions' => 'Use control key for multi-selections',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'multiple' => 1,
			'allow_null' => 0,
			'choices' => array (
				'Central' => 'Central',
				'Window' => 'Window',
				'Wall' => 'Wall',
				'Geothermal' => 'Geothermal',
				'Ductless Mini-Split' => 'Ductless Mini-Split',
				'None' => 'None',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_5887717a81eac',
			'label' => 'Heat',
			'name' => 'heat',
			'type' => 'select',
			'instructions' => 'Use control key for multi-selections',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'multiple' => 1,
			'allow_null' => 0,
			'choices' => array (
				'Forced Air' => 'Forced Air',
				'Baseboard' => 'Baseboard',
				'Hot Water' => 'Hot Water',
				'Gravity' => 'Gravity',
				'Space Heater' => 'Space Heater',
				'Heat Pump' => 'Heat Pump',
				'Steam' => 'Steam',
				'In-Floor Heating' => 'In-Floor Heating',
				'Radiant' => 'Radiant',
				'Geothermal' => 'Geothermal',
				'Ductless Mini-Split' => 'Ductless Mini-Split',
				'Boiler' => 'Boiler',
				'Dual Fuel/Off Peak' => 'Dual Fuel/Off Peak',
				'Fireplace' => 'Fireplace',
				'Wood Stove' => 'Wood Stove',
				'Outdoor Furnace' => 'Outdoor Furnace',
				'Other' => 'Other',
				'None' => 'None',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_58876f9381ea3',
			'label' => 'Fuel',
			'name' => 'fuel',
			'type' => 'select',
			'instructions' => 'Use control key for multi-selections',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'multiple' => 1,
			'allow_null' => 0,
			'choices' => array (
				'Natural Gas' => 'Natural Gas',
				'Oil' => 'Oil',
				'Electric' => 'Electric',
				'Solar' => 'Solar',
				'Propane' => 'Propane',
				'Other' => 'Other',
				'Wood' => 'Wood',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_58876fbe81ea4',
			'label' => 'Water',
			'name' => 'water',
			'type' => 'select',
			'instructions' => 'Use control key for multi-selections',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'multiple' => 1,
			'allow_null' => 0,
			'choices' => array (
				'City Water/Connected' => 'City Water/Connected',
				'City Water - In Street' => 'City Water - In Street',
				'Well' => 'Well',
				'Shared System' => 'Shared System',
				'4-Inch Submersible' => '4-Inch Submersible',
				'Drilled' => 'Drilled',
				'Sand Point' => 'Sand Point',
				'Other' => 'Other',
				'None' => 'None',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_58876fe981ea5',
			'label' => 'Sewer',
			'name' => 'sewer',
			'type' => 'select',
			'instructions' => 'Use control key for multi-selections',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'multiple' => 1,
			'allow_null' => 0,
			'choices' => array (
				'City Sewer/Connected' => 'City Sewer/Connected',
				'City Sewer - In Street' => 'City Sewer - In Street',
				'Private' => 'Private',
				'Shared System' => 'Shared System',
				'Mound' => 'Mound',
				'Holding Tanks' => 'Holding Tanks',
				'Tank with Drainage Field' => 'Tank with Drainage Field',
				'Other' => 'Other',
				'None' => 'None',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_588771ff81eaf',
			'label' => 'Second Unit',
			'name' => 'second_unit',
			'type' => 'select',
			'instructions' => 'Use control key for multi-selections',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'multiple' => 1,
			'allow_null' => 0,
			'choices' => array (
				'Existing In-Law w/Kitchen' => 'Existing In-Law w/Kitchen',
				'Existing In-Law w/Bath' => 'Existing In-Law w/Bath',
				'Formerly Subdivided' => 'Formerly Subdivided',
				'Easily Divided' => 'Easily Divided',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_588cff168fd8d',
			'label' => 'Location',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_587ab6bdc86e8',
			'label' => 'Address, City, State and Zip Code',
			'name' => 'address',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_587abd57ebdb8',
			'label' => 'School District',
			'name' => 'school_district',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_587abd1484b34',
			'label' => 'County',
			'name' => 'county',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_587abd27292a0',
			'label' => 'Postal City',
			'name' => 'postal_city',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_59024a214d6ba',
			'label' => 'Water',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_58876ea181ea0',
			'label' => 'Lake/Waterfront',
			'name' => 'lakewaterfront',
			'type' => 'select',
			'instructions' => 'Use control key for multi-selections',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'multiple' => 1,
			'allow_null' => 0,
			'choices' => array (
				'Lake Front' => 'Lake Front',
				'River Front' => 'River Front',
				'Deeded Access' => 'Deeded Access',
				'Lake View' => 'Lake View',
				'River View' => 'River View',
				'Pond' => 'Pond',
				'Creek/Stream' => 'Creek/Stream',
				'Dock' => 'Dock',
				'Channel Shore' => 'Channel Shore',
				'Association Access' => 'Association Access',
				'Shared' => 'Shared',
				'Lake Superior' => 'Lake Superior',
				'Other' => 'Other',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_588cff338fd8e',
			'label' => 'Tax and Legal Information',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_587abc608a931',
			'label' => 'Legal Description',
			'name' => 'legal_description',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_587ac5606594a',
			'label' => 'Complex/Dev/Sub',
			'name' => 'complexdevsub',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_587abbcae5f35',
			'label' => 'Homestead',
			'name' => 'homestead',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_587aba44ddc60',
			'label' => 'Tax Year',
			'name' => 'tax_year',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_587aba76bb8b4',
			'label' => 'Tax Amount',
			'name' => 'tax_amount',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_587abb034a173',
			'label' => 'Assessment Balance',
			'name' => 'assessment_balance',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_587abb850e3d2',
			'label' => 'Tax With Assessment',
			'name' => 'tax_with_assessment',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_588cff468fd8f',
			'label' => 'Association',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_58876e6681e9f',
			'label' => 'Association Fee Includes',
			'name' => 'association_fee_includes',
			'type' => 'select',
			'instructions' => 'Use control key for multi-selections',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'multiple' => 1,
			'allow_null' => 0,
			'choices' => array (
				'Heating' => 'Heating',
				'Air Conditioning' => 'Air Conditioning',
				'Sanitation' => 'Sanitation',
				'Snow/Lawn Care' => 'Snow/Lawn Care',
				'Outside Maintenance' => 'Outside Maintenance',
				'Hazard Insurance' => 'Hazard Insurance',
				'Electric' => 'Electric',
				'Cable TV' => 'Cable TV',
				'Internet' => 'Internet',
				'Water/Sewer' => 'Water/Sewer',
				'Building Exterior' => 'Building Exterior',
				'Security Staff' => 'Security Staff',
				'Security System' => 'Security System',
				'Professional Mgmt' => 'Professional Mgmt',
				'Dock' => 'Dock',
				'Beach Access' => 'Beach Access',
				'Shared Amenities' => 'Shared Amenities',
				'Parking Space' => 'Parking Space',
				'Valet Parking' => 'Valet Parking',
				'Other' => 'Other',
				'None' => 'None',
				'N/A' => 'N/A',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_5887722481eb0',
			'label' => 'Townhome Characteristics',
			'name' => 'townhome_characteristics',
			'type' => 'select',
			'instructions' => 'Use control key for multi-selections',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'multiple' => 1,
			'allow_null' => 0,
			'choices' => array (
				'Not Applicable' => 'Not Applicable',
				'End Unit' => 'End Unit',
				'Street-Level' => 'Street-Level',
				'Single-Level' => 'Single-Level',
				'Multi-Level' => 'Multi-Level',
				'No Interior Stairs' => 'No Interior Stairs',
				'No Exterior Stairs' => 'No Exterior Stairs',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_5887724a81eb1',
			'label' => 'Assocation Restrictions',
			'name' => 'assocation_restrictions',
			'type' => 'select',
			'instructions' => 'Use control key for multi-selections',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'multiple' => 1,
			'allow_null' => 0,
			'choices' => array (
				'Pets	 Not Allowed' => 'Pets	 Not Allowed',
				'Pets - Cats Allowed' => 'Pets - Cats Allowed',
				'Pets - Dogs Allowed' => 'Pets - Dogs Allowed',
				'Pets - Weight/Height Limit' => 'Pets - Weight/Height Limit',
				'Pets - Number Limit' => 'Pets - Number Limit',
				'Pets - Breed Restriction' => 'Pets - Breed Restriction',
				'Seniors - 55+' => 'Seniors - 55+',
				'Seniors - 62+' => 'Seniors - 62+',
				'Easements' => 'Easements',
				'Rental Restrictions May Apply' => 'Rental Restrictions May Apply',
				'Rentals not Permitted' => 'Rentals not Permitted',
				'Right of first Refusal' => 'Right of first Refusal',
				'Horses/Livestock Allowed' => 'Horses/Livestock Allowed',
				'Architecture Committee' => 'Architecture Committee',
				'Other Bldg Restrictions' => 'Other Bldg Restrictions',
				'Land Leased' => 'Land Leased',
				'Minimum Lot Size' => 'Minimum Lot Size',
				'Other Covenants' => 'Other Covenants',
				'Mandatory Owners Assoc' => 'Mandatory Owners Assoc',
				'Builder Restriction' => 'Builder Restriction',
				'Other' => 'Other',
				'None' => 'None',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_5887727081eb2',
			'label' => 'Townhome Shared Amenities',
			'name' => 'townhome_shared_amenities',
			'type' => 'select',
			'instructions' => 'Use control key for multi-selections',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'multiple' => 1,
			'allow_null' => 0,
			'choices' => array (
				'Deck' => 'Deck',
				'Patio' => 'Patio',
				'Porch' => 'Porch',
				'Tennis Courts' => 'Tennis Courts',
				'Hot Tub' => 'Hot Tub',
				'Sauna' => 'Sauna',
				'Dock' => 'Dock',
				'Beach' => 'Beach',
				'Coin-op Laundry Owned' => 'Coin-op Laundry Owned',
				'Coin-op Laundry Leased' => 'Coin-op Laundry Leased',
				'24 Hour Guard' => '24 Hour Guard',
				'Security Building' => 'Security Building',
				'Lawn Sprinkler' => 'Lawn Sprinkler',
				'Common Garden' => 'Common Garden',
				'Fire Sprinkler System' => 'Fire Sprinkler System',
				'Elevator(s)' => 'Elevator(s)',
				'Car Wash' => 'Car Wash',
				'Concrete Floors & Walls' => 'Concrete Floors & Walls',
				'Other' => 'Other',
				'None' => 'None',
				'Unspecified' => 'Unspecified',
			),
			'default_value' => array (
			),
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'return_format' => 'value',
		),
	),   
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'rental',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));
endif;